### ISSUE TITLE
Fix vite sample application [2 XMR]

### ISSUE THREAD

**Issue by woodser** [woodser/monero-ts#229]
Currently, the [vite sample application](https://github.com/woodser/xmr-sample-vite) supports loading a keys-only wallet in the browser and displaying its keys.

However, http requests [fail to send](https://github.com/woodser/xmr-sample-vite/blob/112c887787758643261603aed3392899b1c59ef5/src/index.ts#L28):

```
TypeError: Cannot read properties of undefined (reading 'call')
        at m.sendJsonRequest (index.js:478:11292)
        at async T.getHeight (index.js:496:42372)
        at async tA (index.js:505:106455)
```

And the [web worker fails to load](https://github.com/woodser/xmr-sample-vite/blob/112c887787758643261603aed3392899b1c59ef5/src/index.ts#L37):

```
TypeError: r.g.fetch is not a function
        at h._onFinish (monero_web_worker.js:2:1543631)
        at e.exports.<anonymous> (monero_web_worker.js:2:1542602)
        at a.emit (monero_web_worker.js:2:1007398)
```

This issue requests fixing the vite sample application so it fully works with monero-ts.

**Comment by mainnet-pat** [comment]
taking a look

**Comment by woodser** [comment]
This issue is resolved with https://github.com/woodser/monero-ts/pull/230 in the v0.10.1 release, and https://github.com/woodser/xmr-sample-vite.
