### ISSUE TITLE
Fix sample React app [0.75 XMR]

### ISSUE THREAD

**Issue by woodser** [woodser/monero-ts#244]
This issue requests fixing the [sample React app](https://github.com/woodser/xmr-sample-react).

Currently when running the app, this error occurs invoking networking requests through Axios in the monero-ts library:

```
Error: Request failed without response: POST https://moneronode.org:18081/json_rpc due to underlying error:
_axios.default.request is not a function
TypeError: _axios.default.request is not a function
    at HttpClient.axiosDigestAuthRequest (http://localhost:3000/static/js/bundle.js:36725:27)
    at http://localhost:3000/static/js/bundle.js:36690:22
```

Installing Axios and making requests directly within the app works as expected.

Essentially `default` is being appended to `axios.default.request` when used through the library, which isn't defined.

Possibly related issue: https://github.com/axios/axios/issues/5044

**Comment by woodser** [comment]
Issue is resolved with https://github.com/woodser/xmr-sample-react/pull/2
