### ISSUE TITLE
WASM Full Wallet `Failed to commit tx`

### ISSUE THREAD

**Issue by gabriellemon** [woodser/monero-ts#245]
Hey all, getting error 
`MoneroError: Failed to commit tx
    at Function.deserializeError (/home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:260:56)
    at Function.invokeWorker (/home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:249:26)
    at async MoneroWalletFullProxy.invokeWorker (/home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletKeys.js:470:12)
    at async MoneroWalletFull.relayTx (/home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWallet.js:875:13)
    at async main (/home/dev/Documents/code-projects/monero-wallet-ts-deno/index.ts:222:12)
Worker error: Error: Failed to commit tx
    at /home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletFull.js:1044:54
    at __emval_call (/home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/dist/monero_wallet_full.js:9:98501)
    at wasm://wasm/015261ae:wasm-function[3684]:0x1bb4ea
    at wasm://wasm/015261ae:wasm-function[4426]:0x23be27
    at wasm://wasm/015261ae:wasm-function[6323]:0x3617c8
    at ret.<computed> (/home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/dist/monero_wallet_full.js:9:82611)
    at invoke_viii (/home/dev/Documents/code-projects/monero-wallet-ts-deno/node_modules/monero-ts/dist/dist/monero_wallet_full.js:9:350510)
    at wasm://wasm/015261ae:wasm-function[7266]:0x3c5fc5
    at wasm://wasm/015261ae:wasm-function[7368]:0x3de0aa
    at wasm://wasm/015261ae:wasm-function[6321]:0x361626 {
  code: undefined
}`

Code: 
``const syncedWallet = await listenReceiveWasmFullWallet(res.address, res.privateViewKey)
//syncedWallet is a fully .sync() wallet
function decimalToAtomicUnits(amount, decimalPlaces) {
  return BigInt(Math.round(amount * 10 ** decimalPlaces));
}
console.info(decimalToAtomicUnits(0.000008, 12))
let tx = await syncedWallet.createTx({
  accountIndex: 0,
  address: "address",
  amount: decimalToAtomicUnits(0.00065, 12), // send 0.00065 XMR (denominated in atomic units)
});

let fee = tx.getFee();  // "Are you sure you want to send... ?"
console.info(fee);
let hash = await syncedWallet.relayTx(tx);``

I can see the correct error when I don't have any enough funds and it is in communication with the daemon. Any ideas?

**Comment by woodser** [comment]
This can happen when there's a tx in the pool which interferes with the tx you're submitting. Maybe mine a block and try again?

**Comment by gabriellemon** [comment]
Thanks for your response @woodser. I am using mainnet though for tokens. I am not sure how mining a block could help. Since during the sync I have a handler that makes sure I have scanned all relevant blocks, I can confirm I have the funds. I have tried sending before and would see the error "I don't have enough money". After lowering the amount, the error went away, but now I see the listed error above.

**Comment by woodser** [comment]
Can you please try with [v0.9.7](https://github.com/woodser/monero-ts/releases/tag/v0.9.7)?

**Comment by gabriellemon** [comment]
I will try and report back. Thank you.

**Comment by gabriellemon** [comment]
Just took a break and re-read my whole code. Found out I was trying to send with a view only wallet. Tested, it with 0.9.7 and it worked flawlessly. My bad.

**Comment by woodser** [comment]
Hm, ok, I recommend updating to the latest, v0.10.3, as there have been fixes, and we would like to know if this issue occurs again. Thanks for reporting back!

**Comment by gabriellemon** [comment]
Tested it again with 0.10.3. Looks good.
